# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: testPython.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='testPython.proto',
  package='Test',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10testPython.proto\x12\x04Test\";\n\x10LevelInfoRequest\x12\x13\n\x0bplayerCoins\x18\x01 \x01(\x05\x12\x12\n\nlevelCoins\x18\x02 \x01(\x05\"9\n\x0eLevelInfoReply\x12\x13\n\x0bplayerCoins\x18\x01 \x01(\x05\x12\x12\n\nlevelCoins\x18\x02 \x01(\x05\x32I\n\x07GetInfo\x12>\n\x0cGetLevelInfo\x12\x16.Test.LevelInfoRequest\x1a\x14.Test.LevelInfoReply\"\x00\x62\x06proto3')
)




_LEVELINFOREQUEST = _descriptor.Descriptor(
  name='LevelInfoRequest',
  full_name='Test.LevelInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerCoins', full_name='Test.LevelInfoRequest.playerCoins', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='levelCoins', full_name='Test.LevelInfoRequest.levelCoins', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=85,
)


_LEVELINFOREPLY = _descriptor.Descriptor(
  name='LevelInfoReply',
  full_name='Test.LevelInfoReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerCoins', full_name='Test.LevelInfoReply.playerCoins', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='levelCoins', full_name='Test.LevelInfoReply.levelCoins', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['LevelInfoRequest'] = _LEVELINFOREQUEST
DESCRIPTOR.message_types_by_name['LevelInfoReply'] = _LEVELINFOREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LevelInfoRequest = _reflection.GeneratedProtocolMessageType('LevelInfoRequest', (_message.Message,), dict(
  DESCRIPTOR = _LEVELINFOREQUEST,
  __module__ = 'testPython_pb2'
  # @@protoc_insertion_point(class_scope:Test.LevelInfoRequest)
  ))
_sym_db.RegisterMessage(LevelInfoRequest)

LevelInfoReply = _reflection.GeneratedProtocolMessageType('LevelInfoReply', (_message.Message,), dict(
  DESCRIPTOR = _LEVELINFOREPLY,
  __module__ = 'testPython_pb2'
  # @@protoc_insertion_point(class_scope:Test.LevelInfoReply)
  ))
_sym_db.RegisterMessage(LevelInfoReply)



_GETINFO = _descriptor.ServiceDescriptor(
  name='GetInfo',
  full_name='Test.GetInfo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=146,
  serialized_end=219,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLevelInfo',
    full_name='Test.GetInfo.GetLevelInfo',
    index=0,
    containing_service=None,
    input_type=_LEVELINFOREQUEST,
    output_type=_LEVELINFOREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETINFO)

DESCRIPTOR.services_by_name['GetInfo'] = _GETINFO

# @@protoc_insertion_point(module_scope)
