# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import testPython_pb2 as testPython__pb2


class GetInfoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetLevelInfo = channel.unary_unary(
        '/Test.GetInfo/GetLevelInfo',
        request_serializer=testPython__pb2.LevelInfoRequest.SerializeToString,
        response_deserializer=testPython__pb2.LevelInfoReply.FromString,
        )


class GetInfoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetLevelInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GetInfoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetLevelInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetLevelInfo,
          request_deserializer=testPython__pb2.LevelInfoRequest.FromString,
          response_serializer=testPython__pb2.LevelInfoReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Test.GetInfo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
