# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import testPython_pb2 as testPython__pb2


class SquareRootServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.squareRoot = channel.unary_unary(
        '/SquareRootService/squareRoot',
        request_serializer=testPython__pb2.Number.SerializeToString,
        response_deserializer=testPython__pb2.Result.FromString,
        )


class SquareRootServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def squareRoot(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SquareRootServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'squareRoot': grpc.unary_unary_rpc_method_handler(
          servicer.squareRoot,
          request_deserializer=testPython__pb2.Number.FromString,
          response_serializer=testPython__pb2.Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SquareRootService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
