// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: test.proto
#ifndef GRPC_test_2eproto__INCLUDED
#define GRPC_test_2eproto__INCLUDED

#include "test.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace Test {

class GetInfo final {
 public:
  static constexpr char const* service_full_name() {
    return "Test.GetInfo";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetLevelInfo(::grpc::ClientContext* context, const ::Test::LevelInfoRequest& request, ::Test::LevelInfoReplay* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Test::LevelInfoReplay>> AsyncGetLevelInfo(::grpc::ClientContext* context, const ::Test::LevelInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Test::LevelInfoReplay>>(AsyncGetLevelInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Test::LevelInfoReplay>> PrepareAsyncGetLevelInfo(::grpc::ClientContext* context, const ::Test::LevelInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Test::LevelInfoReplay>>(PrepareAsyncGetLevelInfoRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetLevelInfo(::grpc::ClientContext* context, const ::Test::LevelInfoRequest* request, ::Test::LevelInfoReplay* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetLevelInfo(::grpc::ClientContext* context, const ::Test::LevelInfoRequest* request, ::Test::LevelInfoReplay* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Test::LevelInfoReplay>* AsyncGetLevelInfoRaw(::grpc::ClientContext* context, const ::Test::LevelInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Test::LevelInfoReplay>* PrepareAsyncGetLevelInfoRaw(::grpc::ClientContext* context, const ::Test::LevelInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetLevelInfo(::grpc::ClientContext* context, const ::Test::LevelInfoRequest& request, ::Test::LevelInfoReplay* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Test::LevelInfoReplay>> AsyncGetLevelInfo(::grpc::ClientContext* context, const ::Test::LevelInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Test::LevelInfoReplay>>(AsyncGetLevelInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Test::LevelInfoReplay>> PrepareAsyncGetLevelInfo(::grpc::ClientContext* context, const ::Test::LevelInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Test::LevelInfoReplay>>(PrepareAsyncGetLevelInfoRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetLevelInfo(::grpc::ClientContext* context, const ::Test::LevelInfoRequest* request, ::Test::LevelInfoReplay* response, std::function<void(::grpc::Status)>) override;
      void GetLevelInfo(::grpc::ClientContext* context, const ::Test::LevelInfoRequest* request, ::Test::LevelInfoReplay* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Test::LevelInfoReplay>* AsyncGetLevelInfoRaw(::grpc::ClientContext* context, const ::Test::LevelInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Test::LevelInfoReplay>* PrepareAsyncGetLevelInfoRaw(::grpc::ClientContext* context, const ::Test::LevelInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetLevelInfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetLevelInfo(::grpc::ServerContext* context, const ::Test::LevelInfoRequest* request, ::Test::LevelInfoReplay* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetLevelInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetLevelInfo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetLevelInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLevelInfo(::grpc::ServerContext* /*context*/, const ::Test::LevelInfoRequest* /*request*/, ::Test::LevelInfoReplay* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetLevelInfo(::grpc::ServerContext* context, ::Test::LevelInfoRequest* request, ::grpc::ServerAsyncResponseWriter< ::Test::LevelInfoReplay>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetLevelInfo<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetLevelInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetLevelInfo() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::Test::LevelInfoRequest, ::Test::LevelInfoReplay>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Test::LevelInfoRequest* request, ::Test::LevelInfoReplay* response) { return this->GetLevelInfo(context, request, response); }));}
    void SetMessageAllocatorFor_GetLevelInfo(
        ::grpc::MessageAllocator< ::Test::LevelInfoRequest, ::Test::LevelInfoReplay>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Test::LevelInfoRequest, ::Test::LevelInfoReplay>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetLevelInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLevelInfo(::grpc::ServerContext* /*context*/, const ::Test::LevelInfoRequest* /*request*/, ::Test::LevelInfoReplay* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetLevelInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::Test::LevelInfoRequest* /*request*/, ::Test::LevelInfoReplay* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetLevelInfo<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetLevelInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetLevelInfo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetLevelInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLevelInfo(::grpc::ServerContext* /*context*/, const ::Test::LevelInfoRequest* /*request*/, ::Test::LevelInfoReplay* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetLevelInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetLevelInfo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetLevelInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLevelInfo(::grpc::ServerContext* /*context*/, const ::Test::LevelInfoRequest* /*request*/, ::Test::LevelInfoReplay* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetLevelInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetLevelInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetLevelInfo() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetLevelInfo(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetLevelInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLevelInfo(::grpc::ServerContext* /*context*/, const ::Test::LevelInfoRequest* /*request*/, ::Test::LevelInfoReplay* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetLevelInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetLevelInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetLevelInfo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Test::LevelInfoRequest, ::Test::LevelInfoReplay>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Test::LevelInfoRequest, ::Test::LevelInfoReplay>* streamer) {
                       return this->StreamedGetLevelInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetLevelInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetLevelInfo(::grpc::ServerContext* /*context*/, const ::Test::LevelInfoRequest* /*request*/, ::Test::LevelInfoReplay* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetLevelInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Test::LevelInfoRequest,::Test::LevelInfoReplay>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetLevelInfo<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetLevelInfo<Service > StreamedService;
};

}  // namespace Test


#endif  // GRPC_test_2eproto__INCLUDED
