# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dawidml/SmartSquareRL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dawidml/SmartSquareRL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dawidml/SmartSquareRL/CMakeFiles /home/dawidml/SmartSquareRL/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dawidml/SmartSquareRL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SmartSquareRL

# Build rule for target.
SmartSquareRL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SmartSquareRL
.PHONY : SmartSquareRL

# fast build rule for target.
SmartSquareRL/fast:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/build
.PHONY : SmartSquareRL/fast

#=============================================================================
# Target rules for targets named gRPC_Client

# Build rule for target.
gRPC_Client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gRPC_Client
.PHONY : gRPC_Client

# fast build rule for target.
gRPC_Client/fast:
	$(MAKE) -f CMakeFiles/gRPC_Client.dir/build.make CMakeFiles/gRPC_Client.dir/build
.PHONY : gRPC_Client/fast

Game/GameFiles/Game.o: Game/GameFiles/Game.cpp.o

.PHONY : Game/GameFiles/Game.o

# target to build an object file
Game/GameFiles/Game.cpp.o:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/Game.cpp.o
.PHONY : Game/GameFiles/Game.cpp.o

Game/GameFiles/Game.i: Game/GameFiles/Game.cpp.i

.PHONY : Game/GameFiles/Game.i

# target to preprocess a source file
Game/GameFiles/Game.cpp.i:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/Game.cpp.i
.PHONY : Game/GameFiles/Game.cpp.i

Game/GameFiles/Game.s: Game/GameFiles/Game.cpp.s

.PHONY : Game/GameFiles/Game.s

# target to generate assembly for a file
Game/GameFiles/Game.cpp.s:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/Game.cpp.s
.PHONY : Game/GameFiles/Game.cpp.s

Game/GameFiles/GameObjects/Box.o: Game/GameFiles/GameObjects/Box.cpp.o

.PHONY : Game/GameFiles/GameObjects/Box.o

# target to build an object file
Game/GameFiles/GameObjects/Box.cpp.o:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Box.cpp.o
.PHONY : Game/GameFiles/GameObjects/Box.cpp.o

Game/GameFiles/GameObjects/Box.i: Game/GameFiles/GameObjects/Box.cpp.i

.PHONY : Game/GameFiles/GameObjects/Box.i

# target to preprocess a source file
Game/GameFiles/GameObjects/Box.cpp.i:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Box.cpp.i
.PHONY : Game/GameFiles/GameObjects/Box.cpp.i

Game/GameFiles/GameObjects/Box.s: Game/GameFiles/GameObjects/Box.cpp.s

.PHONY : Game/GameFiles/GameObjects/Box.s

# target to generate assembly for a file
Game/GameFiles/GameObjects/Box.cpp.s:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Box.cpp.s
.PHONY : Game/GameFiles/GameObjects/Box.cpp.s

Game/GameFiles/GameObjects/Bullet.o: Game/GameFiles/GameObjects/Bullet.cpp.o

.PHONY : Game/GameFiles/GameObjects/Bullet.o

# target to build an object file
Game/GameFiles/GameObjects/Bullet.cpp.o:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Bullet.cpp.o
.PHONY : Game/GameFiles/GameObjects/Bullet.cpp.o

Game/GameFiles/GameObjects/Bullet.i: Game/GameFiles/GameObjects/Bullet.cpp.i

.PHONY : Game/GameFiles/GameObjects/Bullet.i

# target to preprocess a source file
Game/GameFiles/GameObjects/Bullet.cpp.i:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Bullet.cpp.i
.PHONY : Game/GameFiles/GameObjects/Bullet.cpp.i

Game/GameFiles/GameObjects/Bullet.s: Game/GameFiles/GameObjects/Bullet.cpp.s

.PHONY : Game/GameFiles/GameObjects/Bullet.s

# target to generate assembly for a file
Game/GameFiles/GameObjects/Bullet.cpp.s:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Bullet.cpp.s
.PHONY : Game/GameFiles/GameObjects/Bullet.cpp.s

Game/GameFiles/GameObjects/CircleObject.o: Game/GameFiles/GameObjects/CircleObject.cpp.o

.PHONY : Game/GameFiles/GameObjects/CircleObject.o

# target to build an object file
Game/GameFiles/GameObjects/CircleObject.cpp.o:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/CircleObject.cpp.o
.PHONY : Game/GameFiles/GameObjects/CircleObject.cpp.o

Game/GameFiles/GameObjects/CircleObject.i: Game/GameFiles/GameObjects/CircleObject.cpp.i

.PHONY : Game/GameFiles/GameObjects/CircleObject.i

# target to preprocess a source file
Game/GameFiles/GameObjects/CircleObject.cpp.i:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/CircleObject.cpp.i
.PHONY : Game/GameFiles/GameObjects/CircleObject.cpp.i

Game/GameFiles/GameObjects/CircleObject.s: Game/GameFiles/GameObjects/CircleObject.cpp.s

.PHONY : Game/GameFiles/GameObjects/CircleObject.s

# target to generate assembly for a file
Game/GameFiles/GameObjects/CircleObject.cpp.s:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/CircleObject.cpp.s
.PHONY : Game/GameFiles/GameObjects/CircleObject.cpp.s

Game/GameFiles/GameObjects/Coin.o: Game/GameFiles/GameObjects/Coin.cpp.o

.PHONY : Game/GameFiles/GameObjects/Coin.o

# target to build an object file
Game/GameFiles/GameObjects/Coin.cpp.o:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Coin.cpp.o
.PHONY : Game/GameFiles/GameObjects/Coin.cpp.o

Game/GameFiles/GameObjects/Coin.i: Game/GameFiles/GameObjects/Coin.cpp.i

.PHONY : Game/GameFiles/GameObjects/Coin.i

# target to preprocess a source file
Game/GameFiles/GameObjects/Coin.cpp.i:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Coin.cpp.i
.PHONY : Game/GameFiles/GameObjects/Coin.cpp.i

Game/GameFiles/GameObjects/Coin.s: Game/GameFiles/GameObjects/Coin.cpp.s

.PHONY : Game/GameFiles/GameObjects/Coin.s

# target to generate assembly for a file
Game/GameFiles/GameObjects/Coin.cpp.s:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Coin.cpp.s
.PHONY : Game/GameFiles/GameObjects/Coin.cpp.s

Game/GameFiles/GameObjects/Finish.o: Game/GameFiles/GameObjects/Finish.cpp.o

.PHONY : Game/GameFiles/GameObjects/Finish.o

# target to build an object file
Game/GameFiles/GameObjects/Finish.cpp.o:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Finish.cpp.o
.PHONY : Game/GameFiles/GameObjects/Finish.cpp.o

Game/GameFiles/GameObjects/Finish.i: Game/GameFiles/GameObjects/Finish.cpp.i

.PHONY : Game/GameFiles/GameObjects/Finish.i

# target to preprocess a source file
Game/GameFiles/GameObjects/Finish.cpp.i:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Finish.cpp.i
.PHONY : Game/GameFiles/GameObjects/Finish.cpp.i

Game/GameFiles/GameObjects/Finish.s: Game/GameFiles/GameObjects/Finish.cpp.s

.PHONY : Game/GameFiles/GameObjects/Finish.s

# target to generate assembly for a file
Game/GameFiles/GameObjects/Finish.cpp.s:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Finish.cpp.s
.PHONY : Game/GameFiles/GameObjects/Finish.cpp.s

Game/GameFiles/GameObjects/Floor.o: Game/GameFiles/GameObjects/Floor.cpp.o

.PHONY : Game/GameFiles/GameObjects/Floor.o

# target to build an object file
Game/GameFiles/GameObjects/Floor.cpp.o:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Floor.cpp.o
.PHONY : Game/GameFiles/GameObjects/Floor.cpp.o

Game/GameFiles/GameObjects/Floor.i: Game/GameFiles/GameObjects/Floor.cpp.i

.PHONY : Game/GameFiles/GameObjects/Floor.i

# target to preprocess a source file
Game/GameFiles/GameObjects/Floor.cpp.i:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Floor.cpp.i
.PHONY : Game/GameFiles/GameObjects/Floor.cpp.i

Game/GameFiles/GameObjects/Floor.s: Game/GameFiles/GameObjects/Floor.cpp.s

.PHONY : Game/GameFiles/GameObjects/Floor.s

# target to generate assembly for a file
Game/GameFiles/GameObjects/Floor.cpp.s:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Floor.cpp.s
.PHONY : Game/GameFiles/GameObjects/Floor.cpp.s

Game/GameFiles/GameObjects/MovingDanger.o: Game/GameFiles/GameObjects/MovingDanger.cpp.o

.PHONY : Game/GameFiles/GameObjects/MovingDanger.o

# target to build an object file
Game/GameFiles/GameObjects/MovingDanger.cpp.o:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/MovingDanger.cpp.o
.PHONY : Game/GameFiles/GameObjects/MovingDanger.cpp.o

Game/GameFiles/GameObjects/MovingDanger.i: Game/GameFiles/GameObjects/MovingDanger.cpp.i

.PHONY : Game/GameFiles/GameObjects/MovingDanger.i

# target to preprocess a source file
Game/GameFiles/GameObjects/MovingDanger.cpp.i:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/MovingDanger.cpp.i
.PHONY : Game/GameFiles/GameObjects/MovingDanger.cpp.i

Game/GameFiles/GameObjects/MovingDanger.s: Game/GameFiles/GameObjects/MovingDanger.cpp.s

.PHONY : Game/GameFiles/GameObjects/MovingDanger.s

# target to generate assembly for a file
Game/GameFiles/GameObjects/MovingDanger.cpp.s:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/MovingDanger.cpp.s
.PHONY : Game/GameFiles/GameObjects/MovingDanger.cpp.s

Game/GameFiles/GameObjects/Player.o: Game/GameFiles/GameObjects/Player.cpp.o

.PHONY : Game/GameFiles/GameObjects/Player.o

# target to build an object file
Game/GameFiles/GameObjects/Player.cpp.o:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Player.cpp.o
.PHONY : Game/GameFiles/GameObjects/Player.cpp.o

Game/GameFiles/GameObjects/Player.i: Game/GameFiles/GameObjects/Player.cpp.i

.PHONY : Game/GameFiles/GameObjects/Player.i

# target to preprocess a source file
Game/GameFiles/GameObjects/Player.cpp.i:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Player.cpp.i
.PHONY : Game/GameFiles/GameObjects/Player.cpp.i

Game/GameFiles/GameObjects/Player.s: Game/GameFiles/GameObjects/Player.cpp.s

.PHONY : Game/GameFiles/GameObjects/Player.s

# target to generate assembly for a file
Game/GameFiles/GameObjects/Player.cpp.s:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Player.cpp.s
.PHONY : Game/GameFiles/GameObjects/Player.cpp.s

Game/GameFiles/GameObjects/PlayerFoV.o: Game/GameFiles/GameObjects/PlayerFoV.cpp.o

.PHONY : Game/GameFiles/GameObjects/PlayerFoV.o

# target to build an object file
Game/GameFiles/GameObjects/PlayerFoV.cpp.o:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/PlayerFoV.cpp.o
.PHONY : Game/GameFiles/GameObjects/PlayerFoV.cpp.o

Game/GameFiles/GameObjects/PlayerFoV.i: Game/GameFiles/GameObjects/PlayerFoV.cpp.i

.PHONY : Game/GameFiles/GameObjects/PlayerFoV.i

# target to preprocess a source file
Game/GameFiles/GameObjects/PlayerFoV.cpp.i:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/PlayerFoV.cpp.i
.PHONY : Game/GameFiles/GameObjects/PlayerFoV.cpp.i

Game/GameFiles/GameObjects/PlayerFoV.s: Game/GameFiles/GameObjects/PlayerFoV.cpp.s

.PHONY : Game/GameFiles/GameObjects/PlayerFoV.s

# target to generate assembly for a file
Game/GameFiles/GameObjects/PlayerFoV.cpp.s:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/PlayerFoV.cpp.s
.PHONY : Game/GameFiles/GameObjects/PlayerFoV.cpp.s

Game/GameFiles/GameObjects/SquareObject.o: Game/GameFiles/GameObjects/SquareObject.cpp.o

.PHONY : Game/GameFiles/GameObjects/SquareObject.o

# target to build an object file
Game/GameFiles/GameObjects/SquareObject.cpp.o:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/SquareObject.cpp.o
.PHONY : Game/GameFiles/GameObjects/SquareObject.cpp.o

Game/GameFiles/GameObjects/SquareObject.i: Game/GameFiles/GameObjects/SquareObject.cpp.i

.PHONY : Game/GameFiles/GameObjects/SquareObject.i

# target to preprocess a source file
Game/GameFiles/GameObjects/SquareObject.cpp.i:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/SquareObject.cpp.i
.PHONY : Game/GameFiles/GameObjects/SquareObject.cpp.i

Game/GameFiles/GameObjects/SquareObject.s: Game/GameFiles/GameObjects/SquareObject.cpp.s

.PHONY : Game/GameFiles/GameObjects/SquareObject.s

# target to generate assembly for a file
Game/GameFiles/GameObjects/SquareObject.cpp.s:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/SquareObject.cpp.s
.PHONY : Game/GameFiles/GameObjects/SquareObject.cpp.s

Game/GameFiles/GameObjects/StaticDanger.o: Game/GameFiles/GameObjects/StaticDanger.cpp.o

.PHONY : Game/GameFiles/GameObjects/StaticDanger.o

# target to build an object file
Game/GameFiles/GameObjects/StaticDanger.cpp.o:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/StaticDanger.cpp.o
.PHONY : Game/GameFiles/GameObjects/StaticDanger.cpp.o

Game/GameFiles/GameObjects/StaticDanger.i: Game/GameFiles/GameObjects/StaticDanger.cpp.i

.PHONY : Game/GameFiles/GameObjects/StaticDanger.i

# target to preprocess a source file
Game/GameFiles/GameObjects/StaticDanger.cpp.i:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/StaticDanger.cpp.i
.PHONY : Game/GameFiles/GameObjects/StaticDanger.cpp.i

Game/GameFiles/GameObjects/StaticDanger.s: Game/GameFiles/GameObjects/StaticDanger.cpp.s

.PHONY : Game/GameFiles/GameObjects/StaticDanger.s

# target to generate assembly for a file
Game/GameFiles/GameObjects/StaticDanger.cpp.s:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/StaticDanger.cpp.s
.PHONY : Game/GameFiles/GameObjects/StaticDanger.cpp.s

Game/GameFiles/GameObjects/Wall.o: Game/GameFiles/GameObjects/Wall.cpp.o

.PHONY : Game/GameFiles/GameObjects/Wall.o

# target to build an object file
Game/GameFiles/GameObjects/Wall.cpp.o:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Wall.cpp.o
.PHONY : Game/GameFiles/GameObjects/Wall.cpp.o

Game/GameFiles/GameObjects/Wall.i: Game/GameFiles/GameObjects/Wall.cpp.i

.PHONY : Game/GameFiles/GameObjects/Wall.i

# target to preprocess a source file
Game/GameFiles/GameObjects/Wall.cpp.i:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Wall.cpp.i
.PHONY : Game/GameFiles/GameObjects/Wall.cpp.i

Game/GameFiles/GameObjects/Wall.s: Game/GameFiles/GameObjects/Wall.cpp.s

.PHONY : Game/GameFiles/GameObjects/Wall.s

# target to generate assembly for a file
Game/GameFiles/GameObjects/Wall.cpp.s:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameObjects/Wall.cpp.s
.PHONY : Game/GameFiles/GameObjects/Wall.cpp.s

Game/GameFiles/GameStateHandling.o: Game/GameFiles/GameStateHandling.cpp.o

.PHONY : Game/GameFiles/GameStateHandling.o

# target to build an object file
Game/GameFiles/GameStateHandling.cpp.o:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameStateHandling.cpp.o
.PHONY : Game/GameFiles/GameStateHandling.cpp.o

Game/GameFiles/GameStateHandling.i: Game/GameFiles/GameStateHandling.cpp.i

.PHONY : Game/GameFiles/GameStateHandling.i

# target to preprocess a source file
Game/GameFiles/GameStateHandling.cpp.i:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameStateHandling.cpp.i
.PHONY : Game/GameFiles/GameStateHandling.cpp.i

Game/GameFiles/GameStateHandling.s: Game/GameFiles/GameStateHandling.cpp.s

.PHONY : Game/GameFiles/GameStateHandling.s

# target to generate assembly for a file
Game/GameFiles/GameStateHandling.cpp.s:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/GameStateHandling.cpp.s
.PHONY : Game/GameFiles/GameStateHandling.cpp.s

Game/GameFiles/Level.o: Game/GameFiles/Level.cpp.o

.PHONY : Game/GameFiles/Level.o

# target to build an object file
Game/GameFiles/Level.cpp.o:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/Level.cpp.o
.PHONY : Game/GameFiles/Level.cpp.o

Game/GameFiles/Level.i: Game/GameFiles/Level.cpp.i

.PHONY : Game/GameFiles/Level.i

# target to preprocess a source file
Game/GameFiles/Level.cpp.i:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/Level.cpp.i
.PHONY : Game/GameFiles/Level.cpp.i

Game/GameFiles/Level.s: Game/GameFiles/Level.cpp.s

.PHONY : Game/GameFiles/Level.s

# target to generate assembly for a file
Game/GameFiles/Level.cpp.s:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/Level.cpp.s
.PHONY : Game/GameFiles/Level.cpp.s

Game/GameFiles/main.o: Game/GameFiles/main.cpp.o

.PHONY : Game/GameFiles/main.o

# target to build an object file
Game/GameFiles/main.cpp.o:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/main.cpp.o
.PHONY : Game/GameFiles/main.cpp.o

Game/GameFiles/main.i: Game/GameFiles/main.cpp.i

.PHONY : Game/GameFiles/main.i

# target to preprocess a source file
Game/GameFiles/main.cpp.i:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/main.cpp.i
.PHONY : Game/GameFiles/main.cpp.i

Game/GameFiles/main.s: Game/GameFiles/main.cpp.s

.PHONY : Game/GameFiles/main.s

# target to generate assembly for a file
Game/GameFiles/main.cpp.s:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/GameFiles/main.cpp.s
.PHONY : Game/GameFiles/main.cpp.s

Game/ProtoClient/ProtoClient.o: Game/ProtoClient/ProtoClient.cpp.o

.PHONY : Game/ProtoClient/ProtoClient.o

# target to build an object file
Game/ProtoClient/ProtoClient.cpp.o:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/ProtoClient/ProtoClient.cpp.o
.PHONY : Game/ProtoClient/ProtoClient.cpp.o

Game/ProtoClient/ProtoClient.i: Game/ProtoClient/ProtoClient.cpp.i

.PHONY : Game/ProtoClient/ProtoClient.i

# target to preprocess a source file
Game/ProtoClient/ProtoClient.cpp.i:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/ProtoClient/ProtoClient.cpp.i
.PHONY : Game/ProtoClient/ProtoClient.cpp.i

Game/ProtoClient/ProtoClient.s: Game/ProtoClient/ProtoClient.cpp.s

.PHONY : Game/ProtoClient/ProtoClient.s

# target to generate assembly for a file
Game/ProtoClient/ProtoClient.cpp.s:
	$(MAKE) -f CMakeFiles/SmartSquareRL.dir/build.make CMakeFiles/SmartSquareRL.dir/Game/ProtoClient/ProtoClient.cpp.s
.PHONY : Game/ProtoClient/ProtoClient.cpp.s

Game/ProtoClient/ProtoFiles/game.grpc.pb.o: Game/ProtoClient/ProtoFiles/game.grpc.pb.cc.o

.PHONY : Game/ProtoClient/ProtoFiles/game.grpc.pb.o

# target to build an object file
Game/ProtoClient/ProtoFiles/game.grpc.pb.cc.o:
	$(MAKE) -f CMakeFiles/gRPC_Client.dir/build.make CMakeFiles/gRPC_Client.dir/Game/ProtoClient/ProtoFiles/game.grpc.pb.cc.o
.PHONY : Game/ProtoClient/ProtoFiles/game.grpc.pb.cc.o

Game/ProtoClient/ProtoFiles/game.grpc.pb.i: Game/ProtoClient/ProtoFiles/game.grpc.pb.cc.i

.PHONY : Game/ProtoClient/ProtoFiles/game.grpc.pb.i

# target to preprocess a source file
Game/ProtoClient/ProtoFiles/game.grpc.pb.cc.i:
	$(MAKE) -f CMakeFiles/gRPC_Client.dir/build.make CMakeFiles/gRPC_Client.dir/Game/ProtoClient/ProtoFiles/game.grpc.pb.cc.i
.PHONY : Game/ProtoClient/ProtoFiles/game.grpc.pb.cc.i

Game/ProtoClient/ProtoFiles/game.grpc.pb.s: Game/ProtoClient/ProtoFiles/game.grpc.pb.cc.s

.PHONY : Game/ProtoClient/ProtoFiles/game.grpc.pb.s

# target to generate assembly for a file
Game/ProtoClient/ProtoFiles/game.grpc.pb.cc.s:
	$(MAKE) -f CMakeFiles/gRPC_Client.dir/build.make CMakeFiles/gRPC_Client.dir/Game/ProtoClient/ProtoFiles/game.grpc.pb.cc.s
.PHONY : Game/ProtoClient/ProtoFiles/game.grpc.pb.cc.s

Game/ProtoClient/ProtoFiles/game.pb.o: Game/ProtoClient/ProtoFiles/game.pb.cc.o

.PHONY : Game/ProtoClient/ProtoFiles/game.pb.o

# target to build an object file
Game/ProtoClient/ProtoFiles/game.pb.cc.o:
	$(MAKE) -f CMakeFiles/gRPC_Client.dir/build.make CMakeFiles/gRPC_Client.dir/Game/ProtoClient/ProtoFiles/game.pb.cc.o
.PHONY : Game/ProtoClient/ProtoFiles/game.pb.cc.o

Game/ProtoClient/ProtoFiles/game.pb.i: Game/ProtoClient/ProtoFiles/game.pb.cc.i

.PHONY : Game/ProtoClient/ProtoFiles/game.pb.i

# target to preprocess a source file
Game/ProtoClient/ProtoFiles/game.pb.cc.i:
	$(MAKE) -f CMakeFiles/gRPC_Client.dir/build.make CMakeFiles/gRPC_Client.dir/Game/ProtoClient/ProtoFiles/game.pb.cc.i
.PHONY : Game/ProtoClient/ProtoFiles/game.pb.cc.i

Game/ProtoClient/ProtoFiles/game.pb.s: Game/ProtoClient/ProtoFiles/game.pb.cc.s

.PHONY : Game/ProtoClient/ProtoFiles/game.pb.s

# target to generate assembly for a file
Game/ProtoClient/ProtoFiles/game.pb.cc.s:
	$(MAKE) -f CMakeFiles/gRPC_Client.dir/build.make CMakeFiles/gRPC_Client.dir/Game/ProtoClient/ProtoFiles/game.pb.cc.s
.PHONY : Game/ProtoClient/ProtoFiles/game.pb.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... SmartSquareRL"
	@echo "... gRPC_Client"
	@echo "... Game/GameFiles/Game.o"
	@echo "... Game/GameFiles/Game.i"
	@echo "... Game/GameFiles/Game.s"
	@echo "... Game/GameFiles/GameObjects/Box.o"
	@echo "... Game/GameFiles/GameObjects/Box.i"
	@echo "... Game/GameFiles/GameObjects/Box.s"
	@echo "... Game/GameFiles/GameObjects/Bullet.o"
	@echo "... Game/GameFiles/GameObjects/Bullet.i"
	@echo "... Game/GameFiles/GameObjects/Bullet.s"
	@echo "... Game/GameFiles/GameObjects/CircleObject.o"
	@echo "... Game/GameFiles/GameObjects/CircleObject.i"
	@echo "... Game/GameFiles/GameObjects/CircleObject.s"
	@echo "... Game/GameFiles/GameObjects/Coin.o"
	@echo "... Game/GameFiles/GameObjects/Coin.i"
	@echo "... Game/GameFiles/GameObjects/Coin.s"
	@echo "... Game/GameFiles/GameObjects/Finish.o"
	@echo "... Game/GameFiles/GameObjects/Finish.i"
	@echo "... Game/GameFiles/GameObjects/Finish.s"
	@echo "... Game/GameFiles/GameObjects/Floor.o"
	@echo "... Game/GameFiles/GameObjects/Floor.i"
	@echo "... Game/GameFiles/GameObjects/Floor.s"
	@echo "... Game/GameFiles/GameObjects/MovingDanger.o"
	@echo "... Game/GameFiles/GameObjects/MovingDanger.i"
	@echo "... Game/GameFiles/GameObjects/MovingDanger.s"
	@echo "... Game/GameFiles/GameObjects/Player.o"
	@echo "... Game/GameFiles/GameObjects/Player.i"
	@echo "... Game/GameFiles/GameObjects/Player.s"
	@echo "... Game/GameFiles/GameObjects/PlayerFoV.o"
	@echo "... Game/GameFiles/GameObjects/PlayerFoV.i"
	@echo "... Game/GameFiles/GameObjects/PlayerFoV.s"
	@echo "... Game/GameFiles/GameObjects/SquareObject.o"
	@echo "... Game/GameFiles/GameObjects/SquareObject.i"
	@echo "... Game/GameFiles/GameObjects/SquareObject.s"
	@echo "... Game/GameFiles/GameObjects/StaticDanger.o"
	@echo "... Game/GameFiles/GameObjects/StaticDanger.i"
	@echo "... Game/GameFiles/GameObjects/StaticDanger.s"
	@echo "... Game/GameFiles/GameObjects/Wall.o"
	@echo "... Game/GameFiles/GameObjects/Wall.i"
	@echo "... Game/GameFiles/GameObjects/Wall.s"
	@echo "... Game/GameFiles/GameStateHandling.o"
	@echo "... Game/GameFiles/GameStateHandling.i"
	@echo "... Game/GameFiles/GameStateHandling.s"
	@echo "... Game/GameFiles/Level.o"
	@echo "... Game/GameFiles/Level.i"
	@echo "... Game/GameFiles/Level.s"
	@echo "... Game/GameFiles/main.o"
	@echo "... Game/GameFiles/main.i"
	@echo "... Game/GameFiles/main.s"
	@echo "... Game/ProtoClient/ProtoClient.o"
	@echo "... Game/ProtoClient/ProtoClient.i"
	@echo "... Game/ProtoClient/ProtoClient.s"
	@echo "... Game/ProtoClient/ProtoFiles/game.grpc.pb.o"
	@echo "... Game/ProtoClient/ProtoFiles/game.grpc.pb.i"
	@echo "... Game/ProtoClient/ProtoFiles/game.grpc.pb.s"
	@echo "... Game/ProtoClient/ProtoFiles/game.pb.o"
	@echo "... Game/ProtoClient/ProtoFiles/game.pb.i"
	@echo "... Game/ProtoClient/ProtoFiles/game.pb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

