// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_game_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_game_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_game_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_game_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_game_2eproto;
namespace GameMessage {
class Action;
struct ActionDefaultTypeInternal;
extern ActionDefaultTypeInternal _Action_default_instance_;
class Reset;
struct ResetDefaultTypeInternal;
extern ResetDefaultTypeInternal _Reset_default_instance_;
class State;
struct StateDefaultTypeInternal;
extern StateDefaultTypeInternal _State_default_instance_;
}  // namespace GameMessage
PROTOBUF_NAMESPACE_OPEN
template<> ::GameMessage::Action* Arena::CreateMaybeMessage<::GameMessage::Action>(Arena*);
template<> ::GameMessage::Reset* Arena::CreateMaybeMessage<::GameMessage::Reset>(Arena*);
template<> ::GameMessage::State* Arena::CreateMaybeMessage<::GameMessage::State>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace GameMessage {

enum State_ObjectDirection : int {
  State_ObjectDirection_NOT_EXIST = 0,
  State_ObjectDirection_UP = 1,
  State_ObjectDirection_RIGHT = 2,
  State_ObjectDirection_DOWN = 3,
  State_ObjectDirection_LEFT = 4,
  State_ObjectDirection_State_ObjectDirection_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  State_ObjectDirection_State_ObjectDirection_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool State_ObjectDirection_IsValid(int value);
constexpr State_ObjectDirection State_ObjectDirection_ObjectDirection_MIN = State_ObjectDirection_NOT_EXIST;
constexpr State_ObjectDirection State_ObjectDirection_ObjectDirection_MAX = State_ObjectDirection_LEFT;
constexpr int State_ObjectDirection_ObjectDirection_ARRAYSIZE = State_ObjectDirection_ObjectDirection_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* State_ObjectDirection_descriptor();
template<typename T>
inline const std::string& State_ObjectDirection_Name(T enum_t_value) {
  static_assert(::std::is_same<T, State_ObjectDirection>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function State_ObjectDirection_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    State_ObjectDirection_descriptor(), enum_t_value);
}
inline bool State_ObjectDirection_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, State_ObjectDirection* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<State_ObjectDirection>(
    State_ObjectDirection_descriptor(), name, value);
}
enum Action_ActionDirection : int {
  Action_ActionDirection_IDLE = 0,
  Action_ActionDirection_UP = 1,
  Action_ActionDirection_RIGHT = 2,
  Action_ActionDirection_DOWN = 3,
  Action_ActionDirection_LEFT = 4,
  Action_ActionDirection_Action_ActionDirection_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Action_ActionDirection_Action_ActionDirection_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Action_ActionDirection_IsValid(int value);
constexpr Action_ActionDirection Action_ActionDirection_ActionDirection_MIN = Action_ActionDirection_IDLE;
constexpr Action_ActionDirection Action_ActionDirection_ActionDirection_MAX = Action_ActionDirection_LEFT;
constexpr int Action_ActionDirection_ActionDirection_ARRAYSIZE = Action_ActionDirection_ActionDirection_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Action_ActionDirection_descriptor();
template<typename T>
inline const std::string& Action_ActionDirection_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Action_ActionDirection>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Action_ActionDirection_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Action_ActionDirection_descriptor(), enum_t_value);
}
inline bool Action_ActionDirection_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Action_ActionDirection* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Action_ActionDirection>(
    Action_ActionDirection_descriptor(), name, value);
}
// ===================================================================

class State final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GameMessage.State) */ {
 public:
  inline State() : State(nullptr) {}
  ~State() override;
  explicit constexpr State(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  State(const State& from);
  State(State&& from) noexcept
    : State() {
    *this = ::std::move(from);
  }

  inline State& operator=(const State& from) {
    CopyFrom(from);
    return *this;
  }
  inline State& operator=(State&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const State& default_instance() {
    return *internal_default_instance();
  }
  static inline const State* internal_default_instance() {
    return reinterpret_cast<const State*>(
               &_State_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(State& a, State& b) {
    a.Swap(&b);
  }
  inline void Swap(State* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(State* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  State* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<State>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const State& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const State& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(State* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GameMessage.State";
  }
  protected:
  explicit State(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef State_ObjectDirection ObjectDirection;
  static constexpr ObjectDirection NOT_EXIST =
    State_ObjectDirection_NOT_EXIST;
  static constexpr ObjectDirection UP =
    State_ObjectDirection_UP;
  static constexpr ObjectDirection RIGHT =
    State_ObjectDirection_RIGHT;
  static constexpr ObjectDirection DOWN =
    State_ObjectDirection_DOWN;
  static constexpr ObjectDirection LEFT =
    State_ObjectDirection_LEFT;
  static inline bool ObjectDirection_IsValid(int value) {
    return State_ObjectDirection_IsValid(value);
  }
  static constexpr ObjectDirection ObjectDirection_MIN =
    State_ObjectDirection_ObjectDirection_MIN;
  static constexpr ObjectDirection ObjectDirection_MAX =
    State_ObjectDirection_ObjectDirection_MAX;
  static constexpr int ObjectDirection_ARRAYSIZE =
    State_ObjectDirection_ObjectDirection_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  ObjectDirection_descriptor() {
    return State_ObjectDirection_descriptor();
  }
  template<typename T>
  static inline const std::string& ObjectDirection_Name(T enum_t_value) {
    static_assert(::std::is_same<T, ObjectDirection>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function ObjectDirection_Name.");
    return State_ObjectDirection_Name(enum_t_value);
  }
  static inline bool ObjectDirection_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      ObjectDirection* value) {
    return State_ObjectDirection_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kClosestObstacleFieldNumber = 3,
    kClosestCoinFieldNumber = 4,
    kIsClosestObstacleBoxFieldNumber = 1,
    kCoinsNeededFieldNumber = 2,
    kGameOverFieldNumber = 9,
    kClosestEnemyFieldNumber = 5,
    kFinishDirectionFieldNumber = 6,
    kRewardFieldNumber = 7,
    kClockTimeFieldNumber = 8,
    kIterationFieldNumber = 10,
  };
  // .GameMessage.State.ObjectDirection closestObstacle = 3;
  void clear_closestobstacle();
  ::GameMessage::State_ObjectDirection closestobstacle() const;
  void set_closestobstacle(::GameMessage::State_ObjectDirection value);
  private:
  ::GameMessage::State_ObjectDirection _internal_closestobstacle() const;
  void _internal_set_closestobstacle(::GameMessage::State_ObjectDirection value);
  public:

  // .GameMessage.State.ObjectDirection closestCoin = 4;
  void clear_closestcoin();
  ::GameMessage::State_ObjectDirection closestcoin() const;
  void set_closestcoin(::GameMessage::State_ObjectDirection value);
  private:
  ::GameMessage::State_ObjectDirection _internal_closestcoin() const;
  void _internal_set_closestcoin(::GameMessage::State_ObjectDirection value);
  public:

  // bool isClosestObstacleBox = 1;
  void clear_isclosestobstaclebox();
  bool isclosestobstaclebox() const;
  void set_isclosestobstaclebox(bool value);
  private:
  bool _internal_isclosestobstaclebox() const;
  void _internal_set_isclosestobstaclebox(bool value);
  public:

  // bool coinsNeeded = 2;
  void clear_coinsneeded();
  bool coinsneeded() const;
  void set_coinsneeded(bool value);
  private:
  bool _internal_coinsneeded() const;
  void _internal_set_coinsneeded(bool value);
  public:

  // bool gameOver = 9;
  void clear_gameover();
  bool gameover() const;
  void set_gameover(bool value);
  private:
  bool _internal_gameover() const;
  void _internal_set_gameover(bool value);
  public:

  // .GameMessage.State.ObjectDirection closestEnemy = 5;
  void clear_closestenemy();
  ::GameMessage::State_ObjectDirection closestenemy() const;
  void set_closestenemy(::GameMessage::State_ObjectDirection value);
  private:
  ::GameMessage::State_ObjectDirection _internal_closestenemy() const;
  void _internal_set_closestenemy(::GameMessage::State_ObjectDirection value);
  public:

  // .GameMessage.State.ObjectDirection finishDirection = 6;
  void clear_finishdirection();
  ::GameMessage::State_ObjectDirection finishdirection() const;
  void set_finishdirection(::GameMessage::State_ObjectDirection value);
  private:
  ::GameMessage::State_ObjectDirection _internal_finishdirection() const;
  void _internal_set_finishdirection(::GameMessage::State_ObjectDirection value);
  public:

  // int32 reward = 7;
  void clear_reward();
  int32_t reward() const;
  void set_reward(int32_t value);
  private:
  int32_t _internal_reward() const;
  void _internal_set_reward(int32_t value);
  public:

  // int32 clockTime = 8;
  void clear_clocktime();
  int32_t clocktime() const;
  void set_clocktime(int32_t value);
  private:
  int32_t _internal_clocktime() const;
  void _internal_set_clocktime(int32_t value);
  public:

  // int32 iteration = 10;
  void clear_iteration();
  int32_t iteration() const;
  void set_iteration(int32_t value);
  private:
  int32_t _internal_iteration() const;
  void _internal_set_iteration(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:GameMessage.State)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int closestobstacle_;
  int closestcoin_;
  bool isclosestobstaclebox_;
  bool coinsneeded_;
  bool gameover_;
  int closestenemy_;
  int finishdirection_;
  int32_t reward_;
  int32_t clocktime_;
  int32_t iteration_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class Action final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GameMessage.Action) */ {
 public:
  inline Action() : Action(nullptr) {}
  ~Action() override;
  explicit constexpr Action(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Action(const Action& from);
  Action(Action&& from) noexcept
    : Action() {
    *this = ::std::move(from);
  }

  inline Action& operator=(const Action& from) {
    CopyFrom(from);
    return *this;
  }
  inline Action& operator=(Action&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Action& default_instance() {
    return *internal_default_instance();
  }
  static inline const Action* internal_default_instance() {
    return reinterpret_cast<const Action*>(
               &_Action_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Action& a, Action& b) {
    a.Swap(&b);
  }
  inline void Swap(Action* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Action* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Action* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Action>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Action& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Action& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Action* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GameMessage.Action";
  }
  protected:
  explicit Action(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Action_ActionDirection ActionDirection;
  static constexpr ActionDirection IDLE =
    Action_ActionDirection_IDLE;
  static constexpr ActionDirection UP =
    Action_ActionDirection_UP;
  static constexpr ActionDirection RIGHT =
    Action_ActionDirection_RIGHT;
  static constexpr ActionDirection DOWN =
    Action_ActionDirection_DOWN;
  static constexpr ActionDirection LEFT =
    Action_ActionDirection_LEFT;
  static inline bool ActionDirection_IsValid(int value) {
    return Action_ActionDirection_IsValid(value);
  }
  static constexpr ActionDirection ActionDirection_MIN =
    Action_ActionDirection_ActionDirection_MIN;
  static constexpr ActionDirection ActionDirection_MAX =
    Action_ActionDirection_ActionDirection_MAX;
  static constexpr int ActionDirection_ARRAYSIZE =
    Action_ActionDirection_ActionDirection_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  ActionDirection_descriptor() {
    return Action_ActionDirection_descriptor();
  }
  template<typename T>
  static inline const std::string& ActionDirection_Name(T enum_t_value) {
    static_assert(::std::is_same<T, ActionDirection>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function ActionDirection_Name.");
    return Action_ActionDirection_Name(enum_t_value);
  }
  static inline bool ActionDirection_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      ActionDirection* value) {
    return Action_ActionDirection_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kMoveDirectionFieldNumber = 1,
    kShotDirectionFieldNumber = 2,
  };
  // .GameMessage.Action.ActionDirection moveDirection = 1;
  void clear_movedirection();
  ::GameMessage::Action_ActionDirection movedirection() const;
  void set_movedirection(::GameMessage::Action_ActionDirection value);
  private:
  ::GameMessage::Action_ActionDirection _internal_movedirection() const;
  void _internal_set_movedirection(::GameMessage::Action_ActionDirection value);
  public:

  // .GameMessage.Action.ActionDirection shotDirection = 2;
  void clear_shotdirection();
  ::GameMessage::Action_ActionDirection shotdirection() const;
  void set_shotdirection(::GameMessage::Action_ActionDirection value);
  private:
  ::GameMessage::Action_ActionDirection _internal_shotdirection() const;
  void _internal_set_shotdirection(::GameMessage::Action_ActionDirection value);
  public:

  // @@protoc_insertion_point(class_scope:GameMessage.Action)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int movedirection_;
  int shotdirection_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class Reset final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GameMessage.Reset) */ {
 public:
  inline Reset() : Reset(nullptr) {}
  ~Reset() override;
  explicit constexpr Reset(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Reset(const Reset& from);
  Reset(Reset&& from) noexcept
    : Reset() {
    *this = ::std::move(from);
  }

  inline Reset& operator=(const Reset& from) {
    CopyFrom(from);
    return *this;
  }
  inline Reset& operator=(Reset&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Reset& default_instance() {
    return *internal_default_instance();
  }
  static inline const Reset* internal_default_instance() {
    return reinterpret_cast<const Reset*>(
               &_Reset_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Reset& a, Reset& b) {
    a.Swap(&b);
  }
  inline void Swap(Reset* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Reset* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Reset* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Reset>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Reset& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Reset& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Reset* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GameMessage.Reset";
  }
  protected:
  explicit Reset(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResetNeededFieldNumber = 1,
  };
  // bool resetNeeded = 1;
  void clear_resetneeded();
  bool resetneeded() const;
  void set_resetneeded(bool value);
  private:
  bool _internal_resetneeded() const;
  void _internal_set_resetneeded(bool value);
  public:

  // @@protoc_insertion_point(class_scope:GameMessage.Reset)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool resetneeded_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// State

// bool isClosestObstacleBox = 1;
inline void State::clear_isclosestobstaclebox() {
  isclosestobstaclebox_ = false;
}
inline bool State::_internal_isclosestobstaclebox() const {
  return isclosestobstaclebox_;
}
inline bool State::isclosestobstaclebox() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.isClosestObstacleBox)
  return _internal_isclosestobstaclebox();
}
inline void State::_internal_set_isclosestobstaclebox(bool value) {
  
  isclosestobstaclebox_ = value;
}
inline void State::set_isclosestobstaclebox(bool value) {
  _internal_set_isclosestobstaclebox(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.isClosestObstacleBox)
}

// bool coinsNeeded = 2;
inline void State::clear_coinsneeded() {
  coinsneeded_ = false;
}
inline bool State::_internal_coinsneeded() const {
  return coinsneeded_;
}
inline bool State::coinsneeded() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.coinsNeeded)
  return _internal_coinsneeded();
}
inline void State::_internal_set_coinsneeded(bool value) {
  
  coinsneeded_ = value;
}
inline void State::set_coinsneeded(bool value) {
  _internal_set_coinsneeded(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.coinsNeeded)
}

// .GameMessage.State.ObjectDirection closestObstacle = 3;
inline void State::clear_closestobstacle() {
  closestobstacle_ = 0;
}
inline ::GameMessage::State_ObjectDirection State::_internal_closestobstacle() const {
  return static_cast< ::GameMessage::State_ObjectDirection >(closestobstacle_);
}
inline ::GameMessage::State_ObjectDirection State::closestobstacle() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.closestObstacle)
  return _internal_closestobstacle();
}
inline void State::_internal_set_closestobstacle(::GameMessage::State_ObjectDirection value) {
  
  closestobstacle_ = value;
}
inline void State::set_closestobstacle(::GameMessage::State_ObjectDirection value) {
  _internal_set_closestobstacle(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.closestObstacle)
}

// .GameMessage.State.ObjectDirection closestCoin = 4;
inline void State::clear_closestcoin() {
  closestcoin_ = 0;
}
inline ::GameMessage::State_ObjectDirection State::_internal_closestcoin() const {
  return static_cast< ::GameMessage::State_ObjectDirection >(closestcoin_);
}
inline ::GameMessage::State_ObjectDirection State::closestcoin() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.closestCoin)
  return _internal_closestcoin();
}
inline void State::_internal_set_closestcoin(::GameMessage::State_ObjectDirection value) {
  
  closestcoin_ = value;
}
inline void State::set_closestcoin(::GameMessage::State_ObjectDirection value) {
  _internal_set_closestcoin(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.closestCoin)
}

// .GameMessage.State.ObjectDirection closestEnemy = 5;
inline void State::clear_closestenemy() {
  closestenemy_ = 0;
}
inline ::GameMessage::State_ObjectDirection State::_internal_closestenemy() const {
  return static_cast< ::GameMessage::State_ObjectDirection >(closestenemy_);
}
inline ::GameMessage::State_ObjectDirection State::closestenemy() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.closestEnemy)
  return _internal_closestenemy();
}
inline void State::_internal_set_closestenemy(::GameMessage::State_ObjectDirection value) {
  
  closestenemy_ = value;
}
inline void State::set_closestenemy(::GameMessage::State_ObjectDirection value) {
  _internal_set_closestenemy(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.closestEnemy)
}

// .GameMessage.State.ObjectDirection finishDirection = 6;
inline void State::clear_finishdirection() {
  finishdirection_ = 0;
}
inline ::GameMessage::State_ObjectDirection State::_internal_finishdirection() const {
  return static_cast< ::GameMessage::State_ObjectDirection >(finishdirection_);
}
inline ::GameMessage::State_ObjectDirection State::finishdirection() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.finishDirection)
  return _internal_finishdirection();
}
inline void State::_internal_set_finishdirection(::GameMessage::State_ObjectDirection value) {
  
  finishdirection_ = value;
}
inline void State::set_finishdirection(::GameMessage::State_ObjectDirection value) {
  _internal_set_finishdirection(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.finishDirection)
}

// int32 reward = 7;
inline void State::clear_reward() {
  reward_ = 0;
}
inline int32_t State::_internal_reward() const {
  return reward_;
}
inline int32_t State::reward() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.reward)
  return _internal_reward();
}
inline void State::_internal_set_reward(int32_t value) {
  
  reward_ = value;
}
inline void State::set_reward(int32_t value) {
  _internal_set_reward(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.reward)
}

// int32 clockTime = 8;
inline void State::clear_clocktime() {
  clocktime_ = 0;
}
inline int32_t State::_internal_clocktime() const {
  return clocktime_;
}
inline int32_t State::clocktime() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.clockTime)
  return _internal_clocktime();
}
inline void State::_internal_set_clocktime(int32_t value) {
  
  clocktime_ = value;
}
inline void State::set_clocktime(int32_t value) {
  _internal_set_clocktime(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.clockTime)
}

// bool gameOver = 9;
inline void State::clear_gameover() {
  gameover_ = false;
}
inline bool State::_internal_gameover() const {
  return gameover_;
}
inline bool State::gameover() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.gameOver)
  return _internal_gameover();
}
inline void State::_internal_set_gameover(bool value) {
  
  gameover_ = value;
}
inline void State::set_gameover(bool value) {
  _internal_set_gameover(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.gameOver)
}

// int32 iteration = 10;
inline void State::clear_iteration() {
  iteration_ = 0;
}
inline int32_t State::_internal_iteration() const {
  return iteration_;
}
inline int32_t State::iteration() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.iteration)
  return _internal_iteration();
}
inline void State::_internal_set_iteration(int32_t value) {
  
  iteration_ = value;
}
inline void State::set_iteration(int32_t value) {
  _internal_set_iteration(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.iteration)
}

// -------------------------------------------------------------------

// Action

// .GameMessage.Action.ActionDirection moveDirection = 1;
inline void Action::clear_movedirection() {
  movedirection_ = 0;
}
inline ::GameMessage::Action_ActionDirection Action::_internal_movedirection() const {
  return static_cast< ::GameMessage::Action_ActionDirection >(movedirection_);
}
inline ::GameMessage::Action_ActionDirection Action::movedirection() const {
  // @@protoc_insertion_point(field_get:GameMessage.Action.moveDirection)
  return _internal_movedirection();
}
inline void Action::_internal_set_movedirection(::GameMessage::Action_ActionDirection value) {
  
  movedirection_ = value;
}
inline void Action::set_movedirection(::GameMessage::Action_ActionDirection value) {
  _internal_set_movedirection(value);
  // @@protoc_insertion_point(field_set:GameMessage.Action.moveDirection)
}

// .GameMessage.Action.ActionDirection shotDirection = 2;
inline void Action::clear_shotdirection() {
  shotdirection_ = 0;
}
inline ::GameMessage::Action_ActionDirection Action::_internal_shotdirection() const {
  return static_cast< ::GameMessage::Action_ActionDirection >(shotdirection_);
}
inline ::GameMessage::Action_ActionDirection Action::shotdirection() const {
  // @@protoc_insertion_point(field_get:GameMessage.Action.shotDirection)
  return _internal_shotdirection();
}
inline void Action::_internal_set_shotdirection(::GameMessage::Action_ActionDirection value) {
  
  shotdirection_ = value;
}
inline void Action::set_shotdirection(::GameMessage::Action_ActionDirection value) {
  _internal_set_shotdirection(value);
  // @@protoc_insertion_point(field_set:GameMessage.Action.shotDirection)
}

// -------------------------------------------------------------------

// Reset

// bool resetNeeded = 1;
inline void Reset::clear_resetneeded() {
  resetneeded_ = false;
}
inline bool Reset::_internal_resetneeded() const {
  return resetneeded_;
}
inline bool Reset::resetneeded() const {
  // @@protoc_insertion_point(field_get:GameMessage.Reset.resetNeeded)
  return _internal_resetneeded();
}
inline void Reset::_internal_set_resetneeded(bool value) {
  
  resetneeded_ = value;
}
inline void Reset::set_resetneeded(bool value) {
  _internal_set_resetneeded(value);
  // @@protoc_insertion_point(field_set:GameMessage.Reset.resetNeeded)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace GameMessage

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::GameMessage::State_ObjectDirection> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::GameMessage::State_ObjectDirection>() {
  return ::GameMessage::State_ObjectDirection_descriptor();
}
template <> struct is_proto_enum< ::GameMessage::Action_ActionDirection> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::GameMessage::Action_ActionDirection>() {
  return ::GameMessage::Action_ActionDirection_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_game_2eproto
