// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_game_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_game_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_game_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_game_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_game_2eproto;
namespace GameMessage {
class Action;
struct ActionDefaultTypeInternal;
extern ActionDefaultTypeInternal _Action_default_instance_;
class Reset;
struct ResetDefaultTypeInternal;
extern ResetDefaultTypeInternal _Reset_default_instance_;
class State;
struct StateDefaultTypeInternal;
extern StateDefaultTypeInternal _State_default_instance_;
class State_Direction;
struct State_DirectionDefaultTypeInternal;
extern State_DirectionDefaultTypeInternal _State_Direction_default_instance_;
}  // namespace GameMessage
PROTOBUF_NAMESPACE_OPEN
template<> ::GameMessage::Action* Arena::CreateMaybeMessage<::GameMessage::Action>(Arena*);
template<> ::GameMessage::Reset* Arena::CreateMaybeMessage<::GameMessage::Reset>(Arena*);
template<> ::GameMessage::State* Arena::CreateMaybeMessage<::GameMessage::State>(Arena*);
template<> ::GameMessage::State_Direction* Arena::CreateMaybeMessage<::GameMessage::State_Direction>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace GameMessage {

enum Action_ActionDirection : int {
  Action_ActionDirection_IDLE = 0,
  Action_ActionDirection_UP = 1,
  Action_ActionDirection_RIGHT = 2,
  Action_ActionDirection_DOWN = 3,
  Action_ActionDirection_LEFT = 4,
  Action_ActionDirection_Action_ActionDirection_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Action_ActionDirection_Action_ActionDirection_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Action_ActionDirection_IsValid(int value);
constexpr Action_ActionDirection Action_ActionDirection_ActionDirection_MIN = Action_ActionDirection_IDLE;
constexpr Action_ActionDirection Action_ActionDirection_ActionDirection_MAX = Action_ActionDirection_LEFT;
constexpr int Action_ActionDirection_ActionDirection_ARRAYSIZE = Action_ActionDirection_ActionDirection_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Action_ActionDirection_descriptor();
template<typename T>
inline const std::string& Action_ActionDirection_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Action_ActionDirection>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Action_ActionDirection_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Action_ActionDirection_descriptor(), enum_t_value);
}
inline bool Action_ActionDirection_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Action_ActionDirection* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Action_ActionDirection>(
    Action_ActionDirection_descriptor(), name, value);
}
// ===================================================================

class State_Direction final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GameMessage.State.Direction) */ {
 public:
  inline State_Direction() : State_Direction(nullptr) {}
  ~State_Direction() override;
  explicit constexpr State_Direction(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  State_Direction(const State_Direction& from);
  State_Direction(State_Direction&& from) noexcept
    : State_Direction() {
    *this = ::std::move(from);
  }

  inline State_Direction& operator=(const State_Direction& from) {
    CopyFrom(from);
    return *this;
  }
  inline State_Direction& operator=(State_Direction&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const State_Direction& default_instance() {
    return *internal_default_instance();
  }
  static inline const State_Direction* internal_default_instance() {
    return reinterpret_cast<const State_Direction*>(
               &_State_Direction_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(State_Direction& a, State_Direction& b) {
    a.Swap(&b);
  }
  inline void Swap(State_Direction* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(State_Direction* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  State_Direction* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<State_Direction>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const State_Direction& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const State_Direction& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(State_Direction* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GameMessage.State.Direction";
  }
  protected:
  explicit State_Direction(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUpFieldNumber = 1,
    kRightFieldNumber = 2,
    kDownFieldNumber = 3,
    kLeftFieldNumber = 4,
  };
  // bool up = 1;
  void clear_up();
  bool up() const;
  void set_up(bool value);
  private:
  bool _internal_up() const;
  void _internal_set_up(bool value);
  public:

  // bool right = 2;
  void clear_right();
  bool right() const;
  void set_right(bool value);
  private:
  bool _internal_right() const;
  void _internal_set_right(bool value);
  public:

  // bool down = 3;
  void clear_down();
  bool down() const;
  void set_down(bool value);
  private:
  bool _internal_down() const;
  void _internal_set_down(bool value);
  public:

  // bool left = 4;
  void clear_left();
  bool left() const;
  void set_left(bool value);
  private:
  bool _internal_left() const;
  void _internal_set_left(bool value);
  public:

  // @@protoc_insertion_point(class_scope:GameMessage.State.Direction)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool up_;
  bool right_;
  bool down_;
  bool left_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class State final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GameMessage.State) */ {
 public:
  inline State() : State(nullptr) {}
  ~State() override;
  explicit constexpr State(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  State(const State& from);
  State(State&& from) noexcept
    : State() {
    *this = ::std::move(from);
  }

  inline State& operator=(const State& from) {
    CopyFrom(from);
    return *this;
  }
  inline State& operator=(State&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const State& default_instance() {
    return *internal_default_instance();
  }
  static inline const State* internal_default_instance() {
    return reinterpret_cast<const State*>(
               &_State_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(State& a, State& b) {
    a.Swap(&b);
  }
  inline void Swap(State* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(State* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  State* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<State>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const State& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const State& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(State* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GameMessage.State";
  }
  protected:
  explicit State(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef State_Direction Direction;

  // accessors -------------------------------------------------------

  enum : int {
    kClosestObstacleFieldNumber = 4,
    kClosestCoinFieldNumber = 5,
    kClosestEnemyFieldNumber = 6,
    kFinishDirectionFieldNumber = 7,
    kClosestObstacleIsBoxFieldNumber = 1,
    kAllCoinsCollectedFieldNumber = 2,
    kCoinInFoVFieldNumber = 3,
    kGameOverFieldNumber = 10,
    kRewardFieldNumber = 8,
    kClockTimeFieldNumber = 9,
    kIterationFieldNumber = 11,
  };
  // .GameMessage.State.Direction closestObstacle = 4;
  bool has_closestobstacle() const;
  private:
  bool _internal_has_closestobstacle() const;
  public:
  void clear_closestobstacle();
  const ::GameMessage::State_Direction& closestobstacle() const;
  PROTOBUF_NODISCARD ::GameMessage::State_Direction* release_closestobstacle();
  ::GameMessage::State_Direction* mutable_closestobstacle();
  void set_allocated_closestobstacle(::GameMessage::State_Direction* closestobstacle);
  private:
  const ::GameMessage::State_Direction& _internal_closestobstacle() const;
  ::GameMessage::State_Direction* _internal_mutable_closestobstacle();
  public:
  void unsafe_arena_set_allocated_closestobstacle(
      ::GameMessage::State_Direction* closestobstacle);
  ::GameMessage::State_Direction* unsafe_arena_release_closestobstacle();

  // .GameMessage.State.Direction closestCoin = 5;
  bool has_closestcoin() const;
  private:
  bool _internal_has_closestcoin() const;
  public:
  void clear_closestcoin();
  const ::GameMessage::State_Direction& closestcoin() const;
  PROTOBUF_NODISCARD ::GameMessage::State_Direction* release_closestcoin();
  ::GameMessage::State_Direction* mutable_closestcoin();
  void set_allocated_closestcoin(::GameMessage::State_Direction* closestcoin);
  private:
  const ::GameMessage::State_Direction& _internal_closestcoin() const;
  ::GameMessage::State_Direction* _internal_mutable_closestcoin();
  public:
  void unsafe_arena_set_allocated_closestcoin(
      ::GameMessage::State_Direction* closestcoin);
  ::GameMessage::State_Direction* unsafe_arena_release_closestcoin();

  // .GameMessage.State.Direction closestEnemy = 6;
  bool has_closestenemy() const;
  private:
  bool _internal_has_closestenemy() const;
  public:
  void clear_closestenemy();
  const ::GameMessage::State_Direction& closestenemy() const;
  PROTOBUF_NODISCARD ::GameMessage::State_Direction* release_closestenemy();
  ::GameMessage::State_Direction* mutable_closestenemy();
  void set_allocated_closestenemy(::GameMessage::State_Direction* closestenemy);
  private:
  const ::GameMessage::State_Direction& _internal_closestenemy() const;
  ::GameMessage::State_Direction* _internal_mutable_closestenemy();
  public:
  void unsafe_arena_set_allocated_closestenemy(
      ::GameMessage::State_Direction* closestenemy);
  ::GameMessage::State_Direction* unsafe_arena_release_closestenemy();

  // .GameMessage.State.Direction finishDirection = 7;
  bool has_finishdirection() const;
  private:
  bool _internal_has_finishdirection() const;
  public:
  void clear_finishdirection();
  const ::GameMessage::State_Direction& finishdirection() const;
  PROTOBUF_NODISCARD ::GameMessage::State_Direction* release_finishdirection();
  ::GameMessage::State_Direction* mutable_finishdirection();
  void set_allocated_finishdirection(::GameMessage::State_Direction* finishdirection);
  private:
  const ::GameMessage::State_Direction& _internal_finishdirection() const;
  ::GameMessage::State_Direction* _internal_mutable_finishdirection();
  public:
  void unsafe_arena_set_allocated_finishdirection(
      ::GameMessage::State_Direction* finishdirection);
  ::GameMessage::State_Direction* unsafe_arena_release_finishdirection();

  // bool closestObstacleIsBox = 1;
  void clear_closestobstacleisbox();
  bool closestobstacleisbox() const;
  void set_closestobstacleisbox(bool value);
  private:
  bool _internal_closestobstacleisbox() const;
  void _internal_set_closestobstacleisbox(bool value);
  public:

  // bool allCoinsCollected = 2;
  void clear_allcoinscollected();
  bool allcoinscollected() const;
  void set_allcoinscollected(bool value);
  private:
  bool _internal_allcoinscollected() const;
  void _internal_set_allcoinscollected(bool value);
  public:

  // bool coinInFoV = 3;
  void clear_coininfov();
  bool coininfov() const;
  void set_coininfov(bool value);
  private:
  bool _internal_coininfov() const;
  void _internal_set_coininfov(bool value);
  public:

  // bool gameOver = 10;
  void clear_gameover();
  bool gameover() const;
  void set_gameover(bool value);
  private:
  bool _internal_gameover() const;
  void _internal_set_gameover(bool value);
  public:

  // int32 reward = 8;
  void clear_reward();
  int32_t reward() const;
  void set_reward(int32_t value);
  private:
  int32_t _internal_reward() const;
  void _internal_set_reward(int32_t value);
  public:

  // int32 clockTime = 9;
  void clear_clocktime();
  int32_t clocktime() const;
  void set_clocktime(int32_t value);
  private:
  int32_t _internal_clocktime() const;
  void _internal_set_clocktime(int32_t value);
  public:

  // int32 iteration = 11;
  void clear_iteration();
  int32_t iteration() const;
  void set_iteration(int32_t value);
  private:
  int32_t _internal_iteration() const;
  void _internal_set_iteration(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:GameMessage.State)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::GameMessage::State_Direction* closestobstacle_;
  ::GameMessage::State_Direction* closestcoin_;
  ::GameMessage::State_Direction* closestenemy_;
  ::GameMessage::State_Direction* finishdirection_;
  bool closestobstacleisbox_;
  bool allcoinscollected_;
  bool coininfov_;
  bool gameover_;
  int32_t reward_;
  int32_t clocktime_;
  int32_t iteration_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class Action final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GameMessage.Action) */ {
 public:
  inline Action() : Action(nullptr) {}
  ~Action() override;
  explicit constexpr Action(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Action(const Action& from);
  Action(Action&& from) noexcept
    : Action() {
    *this = ::std::move(from);
  }

  inline Action& operator=(const Action& from) {
    CopyFrom(from);
    return *this;
  }
  inline Action& operator=(Action&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Action& default_instance() {
    return *internal_default_instance();
  }
  static inline const Action* internal_default_instance() {
    return reinterpret_cast<const Action*>(
               &_Action_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Action& a, Action& b) {
    a.Swap(&b);
  }
  inline void Swap(Action* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Action* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Action* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Action>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Action& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Action& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Action* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GameMessage.Action";
  }
  protected:
  explicit Action(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Action_ActionDirection ActionDirection;
  static constexpr ActionDirection IDLE =
    Action_ActionDirection_IDLE;
  static constexpr ActionDirection UP =
    Action_ActionDirection_UP;
  static constexpr ActionDirection RIGHT =
    Action_ActionDirection_RIGHT;
  static constexpr ActionDirection DOWN =
    Action_ActionDirection_DOWN;
  static constexpr ActionDirection LEFT =
    Action_ActionDirection_LEFT;
  static inline bool ActionDirection_IsValid(int value) {
    return Action_ActionDirection_IsValid(value);
  }
  static constexpr ActionDirection ActionDirection_MIN =
    Action_ActionDirection_ActionDirection_MIN;
  static constexpr ActionDirection ActionDirection_MAX =
    Action_ActionDirection_ActionDirection_MAX;
  static constexpr int ActionDirection_ARRAYSIZE =
    Action_ActionDirection_ActionDirection_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  ActionDirection_descriptor() {
    return Action_ActionDirection_descriptor();
  }
  template<typename T>
  static inline const std::string& ActionDirection_Name(T enum_t_value) {
    static_assert(::std::is_same<T, ActionDirection>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function ActionDirection_Name.");
    return Action_ActionDirection_Name(enum_t_value);
  }
  static inline bool ActionDirection_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      ActionDirection* value) {
    return Action_ActionDirection_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kMoveDirectionFieldNumber = 1,
    kShotDirectionFieldNumber = 2,
  };
  // .GameMessage.Action.ActionDirection moveDirection = 1;
  void clear_movedirection();
  ::GameMessage::Action_ActionDirection movedirection() const;
  void set_movedirection(::GameMessage::Action_ActionDirection value);
  private:
  ::GameMessage::Action_ActionDirection _internal_movedirection() const;
  void _internal_set_movedirection(::GameMessage::Action_ActionDirection value);
  public:

  // .GameMessage.Action.ActionDirection shotDirection = 2;
  void clear_shotdirection();
  ::GameMessage::Action_ActionDirection shotdirection() const;
  void set_shotdirection(::GameMessage::Action_ActionDirection value);
  private:
  ::GameMessage::Action_ActionDirection _internal_shotdirection() const;
  void _internal_set_shotdirection(::GameMessage::Action_ActionDirection value);
  public:

  // @@protoc_insertion_point(class_scope:GameMessage.Action)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int movedirection_;
  int shotdirection_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class Reset final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GameMessage.Reset) */ {
 public:
  inline Reset() : Reset(nullptr) {}
  ~Reset() override;
  explicit constexpr Reset(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Reset(const Reset& from);
  Reset(Reset&& from) noexcept
    : Reset() {
    *this = ::std::move(from);
  }

  inline Reset& operator=(const Reset& from) {
    CopyFrom(from);
    return *this;
  }
  inline Reset& operator=(Reset&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Reset& default_instance() {
    return *internal_default_instance();
  }
  static inline const Reset* internal_default_instance() {
    return reinterpret_cast<const Reset*>(
               &_Reset_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Reset& a, Reset& b) {
    a.Swap(&b);
  }
  inline void Swap(Reset* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Reset* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Reset* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Reset>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Reset& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Reset& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Reset* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GameMessage.Reset";
  }
  protected:
  explicit Reset(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResetNeededFieldNumber = 1,
  };
  // bool resetNeeded = 1;
  void clear_resetneeded();
  bool resetneeded() const;
  void set_resetneeded(bool value);
  private:
  bool _internal_resetneeded() const;
  void _internal_set_resetneeded(bool value);
  public:

  // @@protoc_insertion_point(class_scope:GameMessage.Reset)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool resetneeded_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_game_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// State_Direction

// bool up = 1;
inline void State_Direction::clear_up() {
  up_ = false;
}
inline bool State_Direction::_internal_up() const {
  return up_;
}
inline bool State_Direction::up() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.Direction.up)
  return _internal_up();
}
inline void State_Direction::_internal_set_up(bool value) {
  
  up_ = value;
}
inline void State_Direction::set_up(bool value) {
  _internal_set_up(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.Direction.up)
}

// bool right = 2;
inline void State_Direction::clear_right() {
  right_ = false;
}
inline bool State_Direction::_internal_right() const {
  return right_;
}
inline bool State_Direction::right() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.Direction.right)
  return _internal_right();
}
inline void State_Direction::_internal_set_right(bool value) {
  
  right_ = value;
}
inline void State_Direction::set_right(bool value) {
  _internal_set_right(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.Direction.right)
}

// bool down = 3;
inline void State_Direction::clear_down() {
  down_ = false;
}
inline bool State_Direction::_internal_down() const {
  return down_;
}
inline bool State_Direction::down() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.Direction.down)
  return _internal_down();
}
inline void State_Direction::_internal_set_down(bool value) {
  
  down_ = value;
}
inline void State_Direction::set_down(bool value) {
  _internal_set_down(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.Direction.down)
}

// bool left = 4;
inline void State_Direction::clear_left() {
  left_ = false;
}
inline bool State_Direction::_internal_left() const {
  return left_;
}
inline bool State_Direction::left() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.Direction.left)
  return _internal_left();
}
inline void State_Direction::_internal_set_left(bool value) {
  
  left_ = value;
}
inline void State_Direction::set_left(bool value) {
  _internal_set_left(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.Direction.left)
}

// -------------------------------------------------------------------

// State

// bool closestObstacleIsBox = 1;
inline void State::clear_closestobstacleisbox() {
  closestobstacleisbox_ = false;
}
inline bool State::_internal_closestobstacleisbox() const {
  return closestobstacleisbox_;
}
inline bool State::closestobstacleisbox() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.closestObstacleIsBox)
  return _internal_closestobstacleisbox();
}
inline void State::_internal_set_closestobstacleisbox(bool value) {
  
  closestobstacleisbox_ = value;
}
inline void State::set_closestobstacleisbox(bool value) {
  _internal_set_closestobstacleisbox(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.closestObstacleIsBox)
}

// bool allCoinsCollected = 2;
inline void State::clear_allcoinscollected() {
  allcoinscollected_ = false;
}
inline bool State::_internal_allcoinscollected() const {
  return allcoinscollected_;
}
inline bool State::allcoinscollected() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.allCoinsCollected)
  return _internal_allcoinscollected();
}
inline void State::_internal_set_allcoinscollected(bool value) {
  
  allcoinscollected_ = value;
}
inline void State::set_allcoinscollected(bool value) {
  _internal_set_allcoinscollected(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.allCoinsCollected)
}

// bool coinInFoV = 3;
inline void State::clear_coininfov() {
  coininfov_ = false;
}
inline bool State::_internal_coininfov() const {
  return coininfov_;
}
inline bool State::coininfov() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.coinInFoV)
  return _internal_coininfov();
}
inline void State::_internal_set_coininfov(bool value) {
  
  coininfov_ = value;
}
inline void State::set_coininfov(bool value) {
  _internal_set_coininfov(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.coinInFoV)
}

// .GameMessage.State.Direction closestObstacle = 4;
inline bool State::_internal_has_closestobstacle() const {
  return this != internal_default_instance() && closestobstacle_ != nullptr;
}
inline bool State::has_closestobstacle() const {
  return _internal_has_closestobstacle();
}
inline void State::clear_closestobstacle() {
  if (GetArenaForAllocation() == nullptr && closestobstacle_ != nullptr) {
    delete closestobstacle_;
  }
  closestobstacle_ = nullptr;
}
inline const ::GameMessage::State_Direction& State::_internal_closestobstacle() const {
  const ::GameMessage::State_Direction* p = closestobstacle_;
  return p != nullptr ? *p : reinterpret_cast<const ::GameMessage::State_Direction&>(
      ::GameMessage::_State_Direction_default_instance_);
}
inline const ::GameMessage::State_Direction& State::closestobstacle() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.closestObstacle)
  return _internal_closestobstacle();
}
inline void State::unsafe_arena_set_allocated_closestobstacle(
    ::GameMessage::State_Direction* closestobstacle) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(closestobstacle_);
  }
  closestobstacle_ = closestobstacle;
  if (closestobstacle) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameMessage.State.closestObstacle)
}
inline ::GameMessage::State_Direction* State::release_closestobstacle() {
  
  ::GameMessage::State_Direction* temp = closestobstacle_;
  closestobstacle_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::GameMessage::State_Direction* State::unsafe_arena_release_closestobstacle() {
  // @@protoc_insertion_point(field_release:GameMessage.State.closestObstacle)
  
  ::GameMessage::State_Direction* temp = closestobstacle_;
  closestobstacle_ = nullptr;
  return temp;
}
inline ::GameMessage::State_Direction* State::_internal_mutable_closestobstacle() {
  
  if (closestobstacle_ == nullptr) {
    auto* p = CreateMaybeMessage<::GameMessage::State_Direction>(GetArenaForAllocation());
    closestobstacle_ = p;
  }
  return closestobstacle_;
}
inline ::GameMessage::State_Direction* State::mutable_closestobstacle() {
  ::GameMessage::State_Direction* _msg = _internal_mutable_closestobstacle();
  // @@protoc_insertion_point(field_mutable:GameMessage.State.closestObstacle)
  return _msg;
}
inline void State::set_allocated_closestobstacle(::GameMessage::State_Direction* closestobstacle) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete closestobstacle_;
  }
  if (closestobstacle) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::GameMessage::State_Direction>::GetOwningArena(closestobstacle);
    if (message_arena != submessage_arena) {
      closestobstacle = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, closestobstacle, submessage_arena);
    }
    
  } else {
    
  }
  closestobstacle_ = closestobstacle;
  // @@protoc_insertion_point(field_set_allocated:GameMessage.State.closestObstacle)
}

// .GameMessage.State.Direction closestCoin = 5;
inline bool State::_internal_has_closestcoin() const {
  return this != internal_default_instance() && closestcoin_ != nullptr;
}
inline bool State::has_closestcoin() const {
  return _internal_has_closestcoin();
}
inline void State::clear_closestcoin() {
  if (GetArenaForAllocation() == nullptr && closestcoin_ != nullptr) {
    delete closestcoin_;
  }
  closestcoin_ = nullptr;
}
inline const ::GameMessage::State_Direction& State::_internal_closestcoin() const {
  const ::GameMessage::State_Direction* p = closestcoin_;
  return p != nullptr ? *p : reinterpret_cast<const ::GameMessage::State_Direction&>(
      ::GameMessage::_State_Direction_default_instance_);
}
inline const ::GameMessage::State_Direction& State::closestcoin() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.closestCoin)
  return _internal_closestcoin();
}
inline void State::unsafe_arena_set_allocated_closestcoin(
    ::GameMessage::State_Direction* closestcoin) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(closestcoin_);
  }
  closestcoin_ = closestcoin;
  if (closestcoin) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameMessage.State.closestCoin)
}
inline ::GameMessage::State_Direction* State::release_closestcoin() {
  
  ::GameMessage::State_Direction* temp = closestcoin_;
  closestcoin_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::GameMessage::State_Direction* State::unsafe_arena_release_closestcoin() {
  // @@protoc_insertion_point(field_release:GameMessage.State.closestCoin)
  
  ::GameMessage::State_Direction* temp = closestcoin_;
  closestcoin_ = nullptr;
  return temp;
}
inline ::GameMessage::State_Direction* State::_internal_mutable_closestcoin() {
  
  if (closestcoin_ == nullptr) {
    auto* p = CreateMaybeMessage<::GameMessage::State_Direction>(GetArenaForAllocation());
    closestcoin_ = p;
  }
  return closestcoin_;
}
inline ::GameMessage::State_Direction* State::mutable_closestcoin() {
  ::GameMessage::State_Direction* _msg = _internal_mutable_closestcoin();
  // @@protoc_insertion_point(field_mutable:GameMessage.State.closestCoin)
  return _msg;
}
inline void State::set_allocated_closestcoin(::GameMessage::State_Direction* closestcoin) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete closestcoin_;
  }
  if (closestcoin) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::GameMessage::State_Direction>::GetOwningArena(closestcoin);
    if (message_arena != submessage_arena) {
      closestcoin = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, closestcoin, submessage_arena);
    }
    
  } else {
    
  }
  closestcoin_ = closestcoin;
  // @@protoc_insertion_point(field_set_allocated:GameMessage.State.closestCoin)
}

// .GameMessage.State.Direction closestEnemy = 6;
inline bool State::_internal_has_closestenemy() const {
  return this != internal_default_instance() && closestenemy_ != nullptr;
}
inline bool State::has_closestenemy() const {
  return _internal_has_closestenemy();
}
inline void State::clear_closestenemy() {
  if (GetArenaForAllocation() == nullptr && closestenemy_ != nullptr) {
    delete closestenemy_;
  }
  closestenemy_ = nullptr;
}
inline const ::GameMessage::State_Direction& State::_internal_closestenemy() const {
  const ::GameMessage::State_Direction* p = closestenemy_;
  return p != nullptr ? *p : reinterpret_cast<const ::GameMessage::State_Direction&>(
      ::GameMessage::_State_Direction_default_instance_);
}
inline const ::GameMessage::State_Direction& State::closestenemy() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.closestEnemy)
  return _internal_closestenemy();
}
inline void State::unsafe_arena_set_allocated_closestenemy(
    ::GameMessage::State_Direction* closestenemy) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(closestenemy_);
  }
  closestenemy_ = closestenemy;
  if (closestenemy) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameMessage.State.closestEnemy)
}
inline ::GameMessage::State_Direction* State::release_closestenemy() {
  
  ::GameMessage::State_Direction* temp = closestenemy_;
  closestenemy_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::GameMessage::State_Direction* State::unsafe_arena_release_closestenemy() {
  // @@protoc_insertion_point(field_release:GameMessage.State.closestEnemy)
  
  ::GameMessage::State_Direction* temp = closestenemy_;
  closestenemy_ = nullptr;
  return temp;
}
inline ::GameMessage::State_Direction* State::_internal_mutable_closestenemy() {
  
  if (closestenemy_ == nullptr) {
    auto* p = CreateMaybeMessage<::GameMessage::State_Direction>(GetArenaForAllocation());
    closestenemy_ = p;
  }
  return closestenemy_;
}
inline ::GameMessage::State_Direction* State::mutable_closestenemy() {
  ::GameMessage::State_Direction* _msg = _internal_mutable_closestenemy();
  // @@protoc_insertion_point(field_mutable:GameMessage.State.closestEnemy)
  return _msg;
}
inline void State::set_allocated_closestenemy(::GameMessage::State_Direction* closestenemy) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete closestenemy_;
  }
  if (closestenemy) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::GameMessage::State_Direction>::GetOwningArena(closestenemy);
    if (message_arena != submessage_arena) {
      closestenemy = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, closestenemy, submessage_arena);
    }
    
  } else {
    
  }
  closestenemy_ = closestenemy;
  // @@protoc_insertion_point(field_set_allocated:GameMessage.State.closestEnemy)
}

// .GameMessage.State.Direction finishDirection = 7;
inline bool State::_internal_has_finishdirection() const {
  return this != internal_default_instance() && finishdirection_ != nullptr;
}
inline bool State::has_finishdirection() const {
  return _internal_has_finishdirection();
}
inline void State::clear_finishdirection() {
  if (GetArenaForAllocation() == nullptr && finishdirection_ != nullptr) {
    delete finishdirection_;
  }
  finishdirection_ = nullptr;
}
inline const ::GameMessage::State_Direction& State::_internal_finishdirection() const {
  const ::GameMessage::State_Direction* p = finishdirection_;
  return p != nullptr ? *p : reinterpret_cast<const ::GameMessage::State_Direction&>(
      ::GameMessage::_State_Direction_default_instance_);
}
inline const ::GameMessage::State_Direction& State::finishdirection() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.finishDirection)
  return _internal_finishdirection();
}
inline void State::unsafe_arena_set_allocated_finishdirection(
    ::GameMessage::State_Direction* finishdirection) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(finishdirection_);
  }
  finishdirection_ = finishdirection;
  if (finishdirection) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GameMessage.State.finishDirection)
}
inline ::GameMessage::State_Direction* State::release_finishdirection() {
  
  ::GameMessage::State_Direction* temp = finishdirection_;
  finishdirection_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::GameMessage::State_Direction* State::unsafe_arena_release_finishdirection() {
  // @@protoc_insertion_point(field_release:GameMessage.State.finishDirection)
  
  ::GameMessage::State_Direction* temp = finishdirection_;
  finishdirection_ = nullptr;
  return temp;
}
inline ::GameMessage::State_Direction* State::_internal_mutable_finishdirection() {
  
  if (finishdirection_ == nullptr) {
    auto* p = CreateMaybeMessage<::GameMessage::State_Direction>(GetArenaForAllocation());
    finishdirection_ = p;
  }
  return finishdirection_;
}
inline ::GameMessage::State_Direction* State::mutable_finishdirection() {
  ::GameMessage::State_Direction* _msg = _internal_mutable_finishdirection();
  // @@protoc_insertion_point(field_mutable:GameMessage.State.finishDirection)
  return _msg;
}
inline void State::set_allocated_finishdirection(::GameMessage::State_Direction* finishdirection) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete finishdirection_;
  }
  if (finishdirection) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::GameMessage::State_Direction>::GetOwningArena(finishdirection);
    if (message_arena != submessage_arena) {
      finishdirection = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, finishdirection, submessage_arena);
    }
    
  } else {
    
  }
  finishdirection_ = finishdirection;
  // @@protoc_insertion_point(field_set_allocated:GameMessage.State.finishDirection)
}

// int32 reward = 8;
inline void State::clear_reward() {
  reward_ = 0;
}
inline int32_t State::_internal_reward() const {
  return reward_;
}
inline int32_t State::reward() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.reward)
  return _internal_reward();
}
inline void State::_internal_set_reward(int32_t value) {
  
  reward_ = value;
}
inline void State::set_reward(int32_t value) {
  _internal_set_reward(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.reward)
}

// int32 clockTime = 9;
inline void State::clear_clocktime() {
  clocktime_ = 0;
}
inline int32_t State::_internal_clocktime() const {
  return clocktime_;
}
inline int32_t State::clocktime() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.clockTime)
  return _internal_clocktime();
}
inline void State::_internal_set_clocktime(int32_t value) {
  
  clocktime_ = value;
}
inline void State::set_clocktime(int32_t value) {
  _internal_set_clocktime(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.clockTime)
}

// bool gameOver = 10;
inline void State::clear_gameover() {
  gameover_ = false;
}
inline bool State::_internal_gameover() const {
  return gameover_;
}
inline bool State::gameover() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.gameOver)
  return _internal_gameover();
}
inline void State::_internal_set_gameover(bool value) {
  
  gameover_ = value;
}
inline void State::set_gameover(bool value) {
  _internal_set_gameover(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.gameOver)
}

// int32 iteration = 11;
inline void State::clear_iteration() {
  iteration_ = 0;
}
inline int32_t State::_internal_iteration() const {
  return iteration_;
}
inline int32_t State::iteration() const {
  // @@protoc_insertion_point(field_get:GameMessage.State.iteration)
  return _internal_iteration();
}
inline void State::_internal_set_iteration(int32_t value) {
  
  iteration_ = value;
}
inline void State::set_iteration(int32_t value) {
  _internal_set_iteration(value);
  // @@protoc_insertion_point(field_set:GameMessage.State.iteration)
}

// -------------------------------------------------------------------

// Action

// .GameMessage.Action.ActionDirection moveDirection = 1;
inline void Action::clear_movedirection() {
  movedirection_ = 0;
}
inline ::GameMessage::Action_ActionDirection Action::_internal_movedirection() const {
  return static_cast< ::GameMessage::Action_ActionDirection >(movedirection_);
}
inline ::GameMessage::Action_ActionDirection Action::movedirection() const {
  // @@protoc_insertion_point(field_get:GameMessage.Action.moveDirection)
  return _internal_movedirection();
}
inline void Action::_internal_set_movedirection(::GameMessage::Action_ActionDirection value) {
  
  movedirection_ = value;
}
inline void Action::set_movedirection(::GameMessage::Action_ActionDirection value) {
  _internal_set_movedirection(value);
  // @@protoc_insertion_point(field_set:GameMessage.Action.moveDirection)
}

// .GameMessage.Action.ActionDirection shotDirection = 2;
inline void Action::clear_shotdirection() {
  shotdirection_ = 0;
}
inline ::GameMessage::Action_ActionDirection Action::_internal_shotdirection() const {
  return static_cast< ::GameMessage::Action_ActionDirection >(shotdirection_);
}
inline ::GameMessage::Action_ActionDirection Action::shotdirection() const {
  // @@protoc_insertion_point(field_get:GameMessage.Action.shotDirection)
  return _internal_shotdirection();
}
inline void Action::_internal_set_shotdirection(::GameMessage::Action_ActionDirection value) {
  
  shotdirection_ = value;
}
inline void Action::set_shotdirection(::GameMessage::Action_ActionDirection value) {
  _internal_set_shotdirection(value);
  // @@protoc_insertion_point(field_set:GameMessage.Action.shotDirection)
}

// -------------------------------------------------------------------

// Reset

// bool resetNeeded = 1;
inline void Reset::clear_resetneeded() {
  resetneeded_ = false;
}
inline bool Reset::_internal_resetneeded() const {
  return resetneeded_;
}
inline bool Reset::resetneeded() const {
  // @@protoc_insertion_point(field_get:GameMessage.Reset.resetNeeded)
  return _internal_resetneeded();
}
inline void Reset::_internal_set_resetneeded(bool value) {
  
  resetneeded_ = value;
}
inline void Reset::set_resetneeded(bool value) {
  _internal_set_resetneeded(value);
  // @@protoc_insertion_point(field_set:GameMessage.Reset.resetNeeded)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace GameMessage

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::GameMessage::Action_ActionDirection> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::GameMessage::Action_ActionDirection>() {
  return ::GameMessage::Action_ActionDirection_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_game_2eproto
