// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: game.proto

#include "game.pb.h"
#include "game.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace Game {

static const char* ExchangeGameState_method_names[] = {
  "/Game.ExchangeGameState/Exchange",
};

std::unique_ptr< ExchangeGameState::Stub> ExchangeGameState::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ExchangeGameState::Stub> stub(new ExchangeGameState::Stub(channel, options));
  return stub;
}

ExchangeGameState::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Exchange_(ExchangeGameState_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ExchangeGameState::Stub::Exchange(::grpc::ClientContext* context, const ::Game::GameState& request, ::Game::Action* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Game::GameState, ::Game::Action, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Exchange_, context, request, response);
}

void ExchangeGameState::Stub::async::Exchange(::grpc::ClientContext* context, const ::Game::GameState* request, ::Game::Action* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Game::GameState, ::Game::Action, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Exchange_, context, request, response, std::move(f));
}

void ExchangeGameState::Stub::async::Exchange(::grpc::ClientContext* context, const ::Game::GameState* request, ::Game::Action* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Exchange_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Game::Action>* ExchangeGameState::Stub::PrepareAsyncExchangeRaw(::grpc::ClientContext* context, const ::Game::GameState& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Game::Action, ::Game::GameState, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Exchange_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Game::Action>* ExchangeGameState::Stub::AsyncExchangeRaw(::grpc::ClientContext* context, const ::Game::GameState& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExchangeRaw(context, request, cq);
  result->StartCall();
  return result;
}

ExchangeGameState::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ExchangeGameState_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ExchangeGameState::Service, ::Game::GameState, ::Game::Action, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ExchangeGameState::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Game::GameState* req,
             ::Game::Action* resp) {
               return service->Exchange(ctx, req, resp);
             }, this)));
}

ExchangeGameState::Service::~Service() {
}

::grpc::Status ExchangeGameState::Service::Exchange(::grpc::ServerContext* context, const ::Game::GameState* request, ::Game::Action* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Game

