# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import game_pb2 as game__pb2


class ExchangeGameStateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Exchange = channel.unary_unary(
                '/GameMessage.ExchangeGameState/Exchange',
                request_serializer=game__pb2.GameState.SerializeToString,
                response_deserializer=game__pb2.Action.FromString,
                )


class ExchangeGameStateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Exchange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExchangeGameStateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Exchange': grpc.unary_unary_rpc_method_handler(
                    servicer.Exchange,
                    request_deserializer=game__pb2.GameState.FromString,
                    response_serializer=game__pb2.Action.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GameMessage.ExchangeGameState', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExchangeGameState(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Exchange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GameMessage.ExchangeGameState/Exchange',
            game__pb2.GameState.SerializeToString,
            game__pb2.Action.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
