# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import game_pb2 as game__pb2


class StateActionExchangeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StateAction = channel.unary_unary(
                '/GameMessage.StateActionExchange/StateAction',
                request_serializer=game__pb2.State.SerializeToString,
                response_deserializer=game__pb2.Action.FromString,
                )
        self.StateReset = channel.unary_unary(
                '/GameMessage.StateActionExchange/StateReset',
                request_serializer=game__pb2.State.SerializeToString,
                response_deserializer=game__pb2.Reset.FromString,
                )


class StateActionExchangeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StateAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StateReset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StateActionExchangeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StateAction': grpc.unary_unary_rpc_method_handler(
                    servicer.StateAction,
                    request_deserializer=game__pb2.State.FromString,
                    response_serializer=game__pb2.Action.SerializeToString,
            ),
            'StateReset': grpc.unary_unary_rpc_method_handler(
                    servicer.StateReset,
                    request_deserializer=game__pb2.State.FromString,
                    response_serializer=game__pb2.Reset.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GameMessage.StateActionExchange', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StateActionExchange(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StateAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GameMessage.StateActionExchange/StateAction',
            game__pb2.State.SerializeToString,
            game__pb2.Action.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StateReset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GameMessage.StateActionExchange/StateReset',
            game__pb2.State.SerializeToString,
            game__pb2.Reset.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
