# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='game.proto',
  package='GameMessage',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ngame.proto\x12\x0bGameMessage\"\xa1\x03\n\x05State\x12\x1c\n\x14\x63losestObstacleIsBox\x18\x01 \x01(\x08\x12\x19\n\x11\x61llCoinsCollected\x18\x02 \x01(\x08\x12\x35\n\x0f\x63losestObstacle\x18\x03 \x01(\x0b\x32\x1c.GameMessage.State.Direction\x12\x31\n\x0b\x63losestCoin\x18\x04 \x01(\x0b\x32\x1c.GameMessage.State.Direction\x12\x32\n\x0c\x63losestEnemy\x18\x05 \x01(\x0b\x32\x1c.GameMessage.State.Direction\x12\x35\n\x0f\x66inishDirection\x18\x06 \x01(\x0b\x32\x1c.GameMessage.State.Direction\x12\x0e\n\x06reward\x18\x07 \x01(\x05\x12\x11\n\tclockTime\x18\x08 \x01(\x05\x12\x10\n\x08gameOver\x18\t \x01(\x08\x12\x11\n\titeration\x18\n \x01(\x05\x1a\x42\n\tDirection\x12\n\n\x02up\x18\x01 \x01(\x08\x12\r\n\x05right\x18\x02 \x01(\x08\x12\x0c\n\x04\x64own\x18\x03 \x01(\x08\x12\x0c\n\x04left\x18\x04 \x01(\x08\"\xc4\x01\n\x06\x41\x63tion\x12:\n\rmoveDirection\x18\x01 \x01(\x0e\x32#.GameMessage.Action.ActionDirection\x12:\n\rshotDirection\x18\x02 \x01(\x0e\x32#.GameMessage.Action.ActionDirection\"B\n\x0f\x41\x63tionDirection\x12\x08\n\x04IDLE\x10\x00\x12\x06\n\x02UP\x10\x01\x12\t\n\x05RIGHT\x10\x02\x12\x08\n\x04\x44OWN\x10\x03\x12\x08\n\x04LEFT\x10\x04\"\x1c\n\x05Reset\x12\x13\n\x0bresetNeeded\x18\x01 \x01(\x08\x32\x87\x01\n\x13StateActionExchange\x12\x38\n\x0bStateAction\x12\x12.GameMessage.State\x1a\x13.GameMessage.Action\"\x00\x12\x36\n\nStateReset\x12\x12.GameMessage.State\x1a\x12.GameMessage.Reset\"\x00\x62\x06proto3'
)



_ACTION_ACTIONDIRECTION = _descriptor.EnumDescriptor(
  name='ActionDirection',
  full_name='GameMessage.Action.ActionDirection',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOWN', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=578,
  serialized_end=644,
)
_sym_db.RegisterEnumDescriptor(_ACTION_ACTIONDIRECTION)


_STATE_DIRECTION = _descriptor.Descriptor(
  name='Direction',
  full_name='GameMessage.State.Direction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='up', full_name='GameMessage.State.Direction.up', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right', full_name='GameMessage.State.Direction.right', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='down', full_name='GameMessage.State.Direction.down', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='left', full_name='GameMessage.State.Direction.left', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=445,
)

_STATE = _descriptor.Descriptor(
  name='State',
  full_name='GameMessage.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='closestObstacleIsBox', full_name='GameMessage.State.closestObstacleIsBox', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='allCoinsCollected', full_name='GameMessage.State.allCoinsCollected', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='closestObstacle', full_name='GameMessage.State.closestObstacle', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='closestCoin', full_name='GameMessage.State.closestCoin', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='closestEnemy', full_name='GameMessage.State.closestEnemy', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='finishDirection', full_name='GameMessage.State.finishDirection', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reward', full_name='GameMessage.State.reward', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clockTime', full_name='GameMessage.State.clockTime', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gameOver', full_name='GameMessage.State.gameOver', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iteration', full_name='GameMessage.State.iteration', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STATE_DIRECTION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=445,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='GameMessage.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='moveDirection', full_name='GameMessage.Action.moveDirection', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shotDirection', full_name='GameMessage.Action.shotDirection', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACTION_ACTIONDIRECTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=644,
)


_RESET = _descriptor.Descriptor(
  name='Reset',
  full_name='GameMessage.Reset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resetNeeded', full_name='GameMessage.Reset.resetNeeded', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=646,
  serialized_end=674,
)

_STATE_DIRECTION.containing_type = _STATE
_STATE.fields_by_name['closestObstacle'].message_type = _STATE_DIRECTION
_STATE.fields_by_name['closestCoin'].message_type = _STATE_DIRECTION
_STATE.fields_by_name['closestEnemy'].message_type = _STATE_DIRECTION
_STATE.fields_by_name['finishDirection'].message_type = _STATE_DIRECTION
_ACTION.fields_by_name['moveDirection'].enum_type = _ACTION_ACTIONDIRECTION
_ACTION.fields_by_name['shotDirection'].enum_type = _ACTION_ACTIONDIRECTION
_ACTION_ACTIONDIRECTION.containing_type = _ACTION
DESCRIPTOR.message_types_by_name['State'] = _STATE
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
DESCRIPTOR.message_types_by_name['Reset'] = _RESET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {

  'Direction' : _reflection.GeneratedProtocolMessageType('Direction', (_message.Message,), {
    'DESCRIPTOR' : _STATE_DIRECTION,
    '__module__' : 'game_pb2'
    # @@protoc_insertion_point(class_scope:GameMessage.State.Direction)
    })
  ,
  'DESCRIPTOR' : _STATE,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:GameMessage.State)
  })
_sym_db.RegisterMessage(State)
_sym_db.RegisterMessage(State.Direction)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:GameMessage.Action)
  })
_sym_db.RegisterMessage(Action)

Reset = _reflection.GeneratedProtocolMessageType('Reset', (_message.Message,), {
  'DESCRIPTOR' : _RESET,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:GameMessage.Reset)
  })
_sym_db.RegisterMessage(Reset)



_STATEACTIONEXCHANGE = _descriptor.ServiceDescriptor(
  name='StateActionExchange',
  full_name='GameMessage.StateActionExchange',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=677,
  serialized_end=812,
  methods=[
  _descriptor.MethodDescriptor(
    name='StateAction',
    full_name='GameMessage.StateActionExchange.StateAction',
    index=0,
    containing_service=None,
    input_type=_STATE,
    output_type=_ACTION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StateReset',
    full_name='GameMessage.StateActionExchange.StateReset',
    index=1,
    containing_service=None,
    input_type=_STATE,
    output_type=_RESET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATEACTIONEXCHANGE)

DESCRIPTOR.services_by_name['StateActionExchange'] = _STATEACTIONEXCHANGE

# @@protoc_insertion_point(module_scope)
